<?php
header("Content-Type: application/json; charset=UTF-8");

$carsData = [
  ["ser" => 1, "brand" => "فورد", "model" => "فيوجن", "color" => "ابيض", "year" => 2019, "category" => "سيدان"],
  ["ser" => 2, "brand" => "هونداي", "model" => "I10", "color" => "فيراني", "year" => 2019, "category" => "اقتصادية"],
  ["ser" => 3, "brand" => "هونداي", "model" => "اكسنت", "color" => "كحلي", "year" => 2020, "category" => "اقتصادية"],
  ["ser" => 4, "brand" => "هونداي", "model" => "النترا", "color" => "اسود", "year" => 2020, "category" => "سيدان"],
  ["ser" => 5, "brand" => "هونداي", "model" => "النترا", "color" => "فيراني", "year" => 2020, "category" => "سيدان"],
  ["ser" => 6, "brand" => "هونداي", "model" => "النترا", "color" => "اسود", "year" => 2020, "category" => "سيدان"],
  ["ser" => 7, "brand" => "هونداي", "model" => "النترا", "color" => "احمر", "year" => 2020, "category" => "سيدان"],
  ["ser" => 8, "brand" => "هونداي", "model" => "النترا", "color" => "فيراني", "year" => 2020, "category" => "سيدان"],
  ["ser" => 9, "brand" => "هونداي", "model" => "اكسنت", "color" => "احمر", "year" => 2020, "category" => "اقتصادية"],
  ["ser" => 10, "brand" => "هونداي", "model" => "النترا", "color" => "احمر", "year" => 2020, "category" => "سيدان"],
  ["ser" => 11, "brand" => "هونداي", "model" => "النترا", "color" => "سلفر ميتالك", "year" => 2020, "category" => "سيدان"],
  ["ser" => 12, "brand" => "هونداي", "model" => "H1", "color" => "اسود", "year" => 2020, "category" => "فان"],
  ["ser" => 13, "brand" => "كيا", "model" => "سيراتو", "color" => "فيراني", "year" => 2022, "category" => "سيدان"],
  ["ser" => 14, "brand" => "كيا", "model" => "سيلتوس", "color" => "خمري", "year" => 2022, "category" => "دفع رباعي"],
  ["ser" => 15, "brand" => "كيا", "model" => "سونيت", "color" => "اسود", "year" => 2022, "category" => "دفع رباعي"],
  ["ser" => 16, "brand" => "كيا", "model" => "سيلتوس", "color" => "اسود", "year" => 2022, "category" => "دفع رباعي"],
  ["ser" => 17, "brand" => "كيا", "model" => "بيجاس", "color" => "فيراني", "year" => 2022, "category" => "اقتصادية"],
  ["ser" => 18, "brand" => "كيا", "model" => "سيلتوس", "color" => "خمري", "year" => 2022, "category" => "دفع رباعي"],
  ["ser" => 19, "brand" => "كيا", "model" => "سيلتوس", "color" => "خمري", "year" => 2022, "category" => "دفع رباعي"],
  ["ser" => 20, "brand" => "كيا", "model" => "سونيت", "color" => "لؤلؤي", "year" => 2022, "category" => "دفع رباعي"],
  ["ser" => 21, "brand" => "كيا", "model" => "سيراتو", "color" => "فيراني", "year" => 2022, "category" => "سيدان"],
  ["ser" => 22, "brand" => "كيا", "model" => "سونيت", "color" => "اسود", "year" => 2022, "category" => "دفع رباعي"],
  ["ser" => 23, "brand" => "تويوتا", "model" => "كامري", "color" => "فيراني ميتالك", "year" => 2022, "category" => "فاخرة"],
  ["ser" => 24, "brand" => "شفروليه", "model" => "كابتيفا", "color" => "اسود", "year" => 2023, "category" => "دفع رباعي"],
  ["ser" => 25, "brand" => "تويوتا", "model" => "كامري", "color" => "فيراني ميتالك", "year" => 2023, "category" => "فاخرة"],
  ["ser" => 26, "brand" => "تويوتا", "model" => "كامري", "color" => "فيراني ميتالك", "year" => 2023, "category" => "فاخرة"],
  ["ser" => 27, "brand" => "تويوتا", "model" => "كامري", "color" => "سلفر ميتالك", "year" => 2023, "category" => "فاخرة"],
  ["ser" => 28, "brand" => "تويوتا", "model" => "كامري", "color" => "سلفر ميتالك", "year" => 2023, "category" => "فاخرة"],
  ["ser" => 29, "brand" => "تويوتا", "model" => "كامري", "color" => "سلفر ميتالك", "year" => 2023, "category" => "فاخرة"],
  ["ser" => 30, "brand" => "شفروليه", "model" => "كابتيفا", "color" => "اسود", "year" => 2023, "category" => "دفع رباعي"],
  ["ser" => 31, "brand" => "شفروليه", "model" => "كابتيفا", "color" => "فيراني", "year" => 2023, "category" => "دفع رباعي"],
  ["ser" => 32, "brand" => "هونداي", "model" => "H1", "color" => "بني", "year" => 2019, "category" => "فان"],
  ["ser" => 33, "brand" => "هونداي", "model" => "H1", "color" => "فيراني", "year" => 2019, "category" => "فان"],
  ["ser" => 34, "brand" => "تويوتا", "model" => "كورولا", "color" => "سلفر ميتالك", "year" => 2023, "category" => "اقتصادية"],
  ["ser" => 35, "brand" => "تويوتا", "model" => "كورولا", "color" => "بحري ميتالك", "year" => 2023, "category" => "اقتصادية"],
  ["ser" => 36, "brand" => "تويوتا", "model" => "كورولا", "color" => "بحري ميتالك", "year" => 2023, "category" => "اقتصادية"],
  ["ser" => 37, "brand" => "تويوتا", "model" => "كورولا", "color" => "بحري ميتالك", "year" => 2023, "category" => "اقتصادية"],
  ["ser" => 38, "brand" => "تويوتا", "model" => "كورولا", "color" => "بحري ميتالك", "year" => 2023, "category" => "اقتصادية"],
  ["ser" => 39, "brand" => "تويوتا", "model" => "كورولا", "color" => "بحري ميتالك", "year" => 2023, "category" => "اقتصادية"],
  ["ser" => 40, "brand" => "كيا", "model" => "بيكانتو", "color" => "فضي", "year" => 2023, "category" => "اقتصادية"],
  ["ser" => 41, "brand" => "كيا", "model" => "بيكانتو", "color" => "اسود", "year" => 2023, "category" => "اقتصادية"],
  ["ser" => 42, "brand" => "كيا", "model" => "بيكانتو", "color" => "فضي", "year" => 2023, "category" => "اقتصادية"],
  ["ser" => 43, "brand" => "كيا", "model" => "بيكانتو", "color" => "اسود", "year" => 2023, "category" => "اقتصادية"],
  ["ser" => 44, "brand" => "هونداي", "model" => "النترا", "color" => "فيراني", "year" => 2020, "category" => "سيدان"],
  ["ser" => 45, "brand" => "هونداي", "model" => "النترا", "color" => "فيراني", "year" => 2025, "category" => "سيدان"],
  ["ser" => 46, "brand" => "هونداي", "model" => "H1", "color" => "اسود", "year" => 2019, "category" => "فان"],
  ["ser" => 47, "brand" => "هونداي", "model" => "sonata", "color" => "كحلي", "year" => 2022, "category" => "فاخرة"],
  ["ser" => 48, "brand" => "هونداي", "model" => "sonata", "color" => "احمر", "year" => 2022, "category" => "فاخرة"],
  ["ser" => 49, "brand" => "هونداي", "model" => "sonata", "color" => "فيراني", "year" => 2022, "category" => "فاخرة"]
];

echo json_encode($carsData, JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT);
